Importing all the libraries required.

In [96]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


Load the Dataset in a DataFrame.


In [4]:
dia_data = pd.read_csv("C:/Users/msset/OneDrive/Tài liệu/For_Python CSV Files/diabetes.csv")
dia_data.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [33]:
# Check for missing data in case of preprocessing required.
dia_data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [51]:
dia_data['Age'].value_counts() #No NaN values identfied
dia_data['DiabetesPedigreeFunction'].value_counts() #No NaN values identfied
dia_data['BMI'].value_counts() #11 values found with Zero
dia_data['Insulin'].value_counts() #374 values found with Zero
dia_data['SkinThickness'].value_counts() #227 values found with Zero
dia_data['BloodPressure'].value_counts() #35 values found with Zero
dia_data['Glucose'].value_counts() #No NaN values identfied
dia_data['Pregnancies'].value_counts() #111 values found with Zero

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [59]:
dia_data['Pregnancies'].value_counts()

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [61]:
#Imputing with median values in dataset containg 'Zero' values.
median_Pregnancies = dia_data['Pregnancies'].median()
median_Pregnancies

3.0

In [66]:
dia_data['Pregnancies'] = dia_data['Pregnancies'].replace(0, median_Pregnancies)

In [67]:
dia_data['Pregnancies'].value_counts()

Pregnancies
3     186
1     135
2     103
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [74]:
median_BloodPressure = dia_data['BloodPressure'].median()
median_BloodPressure
dia_data['BloodPressure'] = dia_data['BloodPressure'].replace(0, median_BloodPressure)

In [76]:
median_SkinThickness = dia_data['SkinThickness'].median()
median_SkinThickness
dia_data['SkinThickness'] = dia_data['SkinThickness'].replace(0, median_SkinThickness)

In [77]:
median_Insulin = dia_data['Insulin'].median()
median_Insulin
dia_data['Insulin'] = dia_data['Insulin'].replace(0, median_Insulin)

In [78]:
median_BMI = dia_data['BMI'].median()
median_BMI
dia_data['BMI'] = dia_data['BMI'].replace(0, median_BMI)

Seperating Target Columns and Features 

In [79]:
x = dia_data.drop('Outcome', axis=1)


In [80]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35     30.5  33.6   
1            1       85             66             29     30.5  26.6   
2            8      183             64             23     30.5  23.3   
3            1       89             66             23     94.0  28.1   
4            3      137             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

Scale the Data

In [81]:
sc = StandardScaler()

In [82]:
sc = sc.fit_transform(x)

In [83]:
sc

array([[ 0.57007018,  0.84832379, -0.03198993, ...,  0.16724016,
         0.46849198,  1.4259954 ],
       [-1.08580689, -1.12339636, -0.5283186 , ..., -0.85155088,
        -0.36506078, -0.19067191],
       [ 1.23242101,  1.94372388, -0.69376149, ..., -1.33183808,
         0.60439732, -0.10558415],
       ...,
       [ 0.23889477,  0.00330087, -0.03198993, ..., -0.90976751,
        -0.68519336, -0.27575966],
       [-1.08580689,  0.1597866 , -1.02464727, ..., -0.34215536,
        -0.37110101,  1.17073215],
       [-1.08580689, -0.8730192 , -0.19743282, ..., -0.29849289,
        -0.47378505, -0.87137393]])

In [84]:
x = sc
y = dia_data['Outcome']

In [85]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Train Test Split

In [86]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)

Trainig Model Creation using SVM

In [87]:
clf = svm.SVC(kernel='linear')

In [88]:
clf.fit(x_train,y_train)

SVC(kernel='linear')

In [89]:
y_pred = clf.predict(x_test)

In [90]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [91]:
y_test

668    0
324    0
624    0
690    0
473    0
      ..
554    0
319    1
594    0
6      1
615    0
Name: Outcome, Length: 192, dtype: int64

In [94]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.734375

In [103]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [104]:
precision

0.6363636363636364

In [105]:
recall

0.6086956521739131

In [106]:
f1

0.6222222222222223

In [107]:
confusion

array([[99, 24],
       [27, 42]], dtype=int64)

In [97]:
mse = mean_squared_error(y_test, y_pred)
mse

0.265625

In [98]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [99]:
mae

0.265625

In [100]:
r2

-0.1537645811240722

Using Logistics Regression

In [108]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [109]:
y_pred_lr = lr.predict(x_test)

In [110]:
y_pred_lr

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [111]:
accuracy_lr= accuracy_score(y_test, y_pred_lr)
accuracy_lr

0.7291666666666666

Using KNN Classifier

In [112]:
from sklearn.neighbors import KNeighborsClassifier

metric_k = []
neighbors = np.arange(5,25)

for k in neighbors:
  classifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski',p=2)
  classifier.fit(x_train,y_train)
  y_pred_knn= classifier.predict(x_test)
  acc = accuracy_score(y_test,y_pred_knn)
  metric_k.append(acc)

In [113]:
metric_k

[0.671875,
 0.7083333333333334,
 0.71875,
 0.7291666666666666,
 0.7135416666666666,
 0.7291666666666666,
 0.71875,
 0.7291666666666666,
 0.7239583333333334,
 0.7291666666666666,
 0.7395833333333334,
 0.7604166666666666,
 0.7447916666666666,
 0.734375,
 0.7447916666666666,
 0.734375,
 0.7291666666666666,
 0.7447916666666666,
 0.734375,
 0.75]

In [120]:
classifier = KNeighborsClassifier(n_neighbors = 25, metric = 'minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=25)

In [121]:
y_pred_knn = classifier.predict(x_test)
accuracy_score(y_test, y_pred_knn)


0.734375

Using GaussianNaiveBayes

In [122]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [123]:
gnb.fit(x_train, y_train)

GaussianNB()

In [124]:
y_pred_gnb = gnb.predict(x_test)
accuracy_score(y_test, y_pred_gnb)

0.7291666666666666